.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/AesKeySize.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/AesKeySize.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Options\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBToolbox\&.Core\&.Options\&.AesKeySize\fP { \fBToolbox\&.Core\&.Options\&.Aes128\fP = 128, \fBToolbox\&.Core\&.Options\&.Aes192\fP = 192, \fBToolbox\&.Core\&.Options\&.Aes256\fP = 256 }"
.br
.RI "Specifies the AES key size in bits\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
