.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/ApiAuthenticationMode.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/ApiAuthenticationMode.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Options\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBToolbox\&.Core\&.Options\&.ApiAuthenticationMode\fP { \fBToolbox\&.Core\&.Options\&.Anonymous\fP = 0, \fBToolbox\&.Core\&.Options\&.BearerToken\fP = 1, \fBToolbox\&.Core\&.Options\&.Basic\fP = 2, \fBToolbox\&.Core\&.Options\&.ApiKey\fP = 3, \fBToolbox\&.Core\&.Options\&.Certificate\fP = 4, \fBToolbox\&.Core\&.Options\&.OAuth2ClientCredentials\fP = 5 }"
.br
.RI "Specifies the authentication mode for API requests\&. "
.ti -1c
.RI "enum \fBToolbox\&.Core\&.Options\&.ApiKeyLocation\fP { \fBToolbox\&.Core\&.Options\&.Header\fP = 0, \fBToolbox\&.Core\&.Options\&.QueryString\fP = 1 }"
.br
.RI "Specifies where to send the API key\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
