.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Services/Cryptography/Base64CryptographyService.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Services/Cryptography/Base64CryptographyService.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Core\&.Services\&.Cryptography\&.Base64CryptographyService\fP"
.br
.RI "\fBCryptography\fP service implementation using Base64 encoding\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Services\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Services\&.Cryptography\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
