.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Extensions Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Extensions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApiServiceCollectionExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBCryptographyServiceCollectionExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBFileTransferServiceCollectionExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBMailingServiceCollectionExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBOpenTelemetryExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBServiceCollectionExtensions\&.cs\fP"
.br
.in -1c
