.TH "C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Regression Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Regression Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOptionsSchemaTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTelemetryConstantsTests\&.cs\fP"
.br
.in -1c
