.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Base Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Base Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBaseAsyncDisposableService\&.cs\fP"
.br
.ti -1c
.RI "file \fBBaseDisposableService\&.cs\fP"
.br
.in -1c
