.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBServices\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIAsyncDisposableService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDisposableService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIInstrumentedService\&.cs\fP"
.br
.in -1c
