.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions/Services Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions/Services Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIApiService\&.cs\fP"
.br
.ti -1c
.RI "file \fBICryptographyService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIFileTransferService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMailingService\&.cs\fP"
.br
.in -1c
