.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/obj/Debug/net10.0 Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/obj/Debug/net10.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v10\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBToolbox\&.Core\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBToolbox\&.Core\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
