.TH "C:/Users/micde/RiderProjects/Toolbox/samples/Toolbox.Sample Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/samples/Toolbox.Sample Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBProgram\&.cs\fP"
.br
.in -1c
