.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options Directory Reference" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAesKeySize\&.cs\fP"
.br
.ti -1c
.RI "file \fBApiAuthenticationMode\&.cs\fP"
.br
.ti -1c
.RI "file \fBApiOptions\&.cs\fP"
.br
.ti -1c
.RI "file \fBApiRequest\&.cs\fP"
.br
.ti -1c
.RI "file \fBApiResponse\&.cs\fP"
.br
.ti -1c
.RI "file \fBBase64CryptographyOptions\&.cs\fP"
.br
.ti -1c
.RI "file \fBBase64EncodingTable\&.cs\fP"
.br
.ti -1c
.RI "file \fBEmailAddress\&.cs\fP"
.br
.ti -1c
.RI "file \fBEmailAttachment\&.cs\fP"
.br
.ti -1c
.RI "file \fBEmailMessage\&.cs\fP"
.br
.ti -1c
.RI "file \fBFileTransferOptions\&.cs\fP"
.br
.ti -1c
.RI "file \fBFileTransferProtocol\&.cs\fP"
.br
.ti -1c
.RI "file \fBMailingOptions\&.cs\fP"
.br
.ti -1c
.RI "file \fBRsaKeyPair\&.cs\fP"
.br
.ti -1c
.RI "file \fBRsaKeySize\&.cs\fP"
.br
.ti -1c
.RI "file \fBRsaPaddingMode\&.cs\fP"
.br
.ti -1c
.RI "file \fBSmtpSecurityMode\&.cs\fP"
.br
.ti -1c
.RI "file \fBToolboxOptions\&.cs\fP"
.br
.ti -1c
.RI "file \fBToolboxTelemetryOptions\&.cs\fP"
.br
.in -1c
