.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Extensions/CryptographyServiceCollectionExtensions.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Extensions/CryptographyServiceCollectionExtensions.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Core\&.Extensions\&.CryptographyServiceCollectionExtensions\fP"
.br
.RI "Extension methods for IServiceCollection to configure cryptography services\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Extensions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
