.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/EmailMessage.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/EmailMessage.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Core\&.Options\&.EmailMessage\fP"
.br
.RI "Represents an email message to be sent\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Options\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBToolbox\&.Core\&.Options\&.EmailPriority\fP { \fBToolbox\&.Core\&.Options\&.Low\fP = 0, \fBToolbox\&.Core\&.Options\&.Normal\fP = 1, \fBToolbox\&.Core\&.Options\&.High\fP = 2 }"
.br
.RI "Specifies the priority of an email message\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
