.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/EmailAddress.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/EmailAddress.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Options\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBToolbox\&.Core\&.Options\&.EmailAddress\fP (string Address, string? DisplayName=null)"
.br
.RI "Represents an email address with an optional display name\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
