.TH "C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Unit/Services/Api/HttpApiServiceTests.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Unit/Services/Api/HttpApiServiceTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Tests\&.Unit\&.Services\&.Api\&.HttpApiServiceTests\fP"
.br
.RI "\fBUnit\fP tests for \fBHttpApiService\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\&.Unit\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\&.Unit\&.Services\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\&.Unit\&.Services\&.Api\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBMsOptions\fP = Microsoft\&.Extensions\&.Options\&.Options"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBMsOptions\fP = Microsoft\&.Extensions\&.Options\&.Options"

.PP
Definition at line \fB5\fP of file \fBHttpApiServiceTests\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
