.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions/Services/IFileTransferService.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions/Services/IFileTransferService.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP"
.br
.RI "Defines the contract for file transfer services supporting FTP and SFTP protocols\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Abstractions\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Abstractions\&.Services\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
