.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions/IInstrumentedService.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Abstractions/IInstrumentedService.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBToolbox\&.Core\&.Abstractions\&.IInstrumentedService\fP"
.br
.RI "Interface for services that expose OpenTelemetry instrumentation\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Abstractions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
