.TH "ISampleService" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ISampleService \- Sample service interface demonstrating \fBToolbox\fP patterns\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSampleService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task \fBDoWorkAsync\fP (string message, CancellationToken ct=default)"
.br
.RI "Performs sample work asynchronously\&. "
.in -1c
.SH "Detailed Description"
.PP 
Sample service interface demonstrating \fBToolbox\fP patterns\&. 
.PP
Definition at line \fB55\fP of file \fBProgram\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task ISampleService\&.DoWorkAsync (string message, CancellationToken ct = \fRdefault\fP)"

.PP
Performs sample work asynchronously\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP The message to process\&.
.br
\fIct\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task representing the async operation\&.
.RE
.PP

.PP
Implemented in \fBSampleService\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
