.TH "C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Unit/Extensions/MailingServiceCollectionExtensionsTests.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Unit/Extensions/MailingServiceCollectionExtensionsTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\fP"
.br
.RI "\fBUnit\fP tests for MailingServiceCollectionExtensions\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\&.Unit\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\&.Unit\&.Extensions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
