.TH "C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Regression/OptionsSchemaTests.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/tests/Toolbox.Tests/Regression/OptionsSchemaTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Tests\&.Regression\&.OptionsSchemaTests\fP"
.br
.RI "\fBRegression\fP tests for options classes to detect breaking changes in configuration schema\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Tests\&.Regression\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
