.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/RsaKeySize.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/RsaKeySize.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Options\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBToolbox\&.Core\&.Options\&.RsaKeySize\fP { \fBToolbox\&.Core\&.Options\&.Rsa512\fP = 512, \fBToolbox\&.Core\&.Options\&.Rsa1024\fP = 1024, \fBToolbox\&.Core\&.Options\&.Rsa2048\fP = 2048, \fBToolbox\&.Core\&.Options\&.Rsa4096\fP = 4096, \fBToolbox\&.Core\&.Options\&.Rsa8192\fP = 8192, \fBToolbox\&.Core\&.Options\&.Rsa16384\fP = 16384 }"
.br
.RI "Specifies the RSA key size in bits\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
