.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/SmtpSecurityMode.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Options/SmtpSecurityMode.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Options\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBToolbox\&.Core\&.Options\&.SmtpSecurityMode\fP { \fBToolbox\&.Core\&.Options\&.Auto\fP = 0, \fBToolbox\&.Core\&.Options\&.None\fP = 1, \fBToolbox\&.Core\&.Options\&.StartTls\fP = 2, \fBToolbox\&.Core\&.Options\&.StartTlsWhenAvailable\fP = 3, \fBToolbox\&.Core\&.Options\&.SslOnConnect\fP = 4 }"
.br
.RI "Specifies the security mode for SMTP connections\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
