.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Services/Mailing/SmtpMailingService.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Services/Mailing/SmtpMailingService.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Core\&.Services\&.Mailing\&.SmtpMailingService\fP"
.br
.RI "Email sending service implementation using SMTP with MailKit\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Services\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Services\&.Mailing\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
