.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Telemetry/TelemetryConstants.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/Telemetry/TelemetryConstants.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\fP"
.br
.RI "Constants used for OpenTelemetry instrumentation across \fBToolbox\fP services\&. "
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\&.Attributes\fP"
.br
.RI "Standard attribute names for service telemetry\&. "
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\&.Metrics\fP"
.br
.RI "Standard metric names for service instrumentation\&. "
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\&.CryptoAttributes\fP"
.br
.RI "Additional attribute names for specific service categories\&. "
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\&.FileTransferAttributes\fP"
.br
.RI "Additional attribute names for file transfer services\&. "
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\&.MailingAttributes\fP"
.br
.RI "Additional attribute names for mailing services\&. "
.ti -1c
.RI "class \fBToolbox\&.Core\&.Telemetry\&.TelemetryConstants\&.ApiAttributes\fP"
.br
.RI "Additional attribute names for API services\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBToolbox\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBToolbox\&.Core\&.Telemetry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
