.TH "Toolbox.Tests.Unit.Options.ApiRequestTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.Options.ApiRequestTests \- \fBUnit\fP tests for \fBApiRequest\fP and related classes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor_WithValidParameters_ShouldCreate\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_ShouldUppercaseMethod\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithNullMethod_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithNullUrl_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBGet_ShouldCreateGetRequest\fP ()"
.br
.ti -1c
.RI "void \fBPost_ShouldCreatePostRequest\fP ()"
.br
.ti -1c
.RI "void \fBPost_WithBody_ShouldSetJsonContent\fP ()"
.br
.ti -1c
.RI "void \fBPut_ShouldCreatePutRequest\fP ()"
.br
.ti -1c
.RI "void \fBPatch_ShouldCreatePatchRequest\fP ()"
.br
.ti -1c
.RI "void \fBDelete_ShouldCreateDeleteRequest\fP ()"
.br
.ti -1c
.RI "void \fBHead_ShouldCreateHeadRequest\fP ()"
.br
.ti -1c
.RI "void \fBOptions_ShouldCreateOptionsRequest\fP ()"
.br
.ti -1c
.RI "void \fBWithHeader_ShouldAddHeader\fP ()"
.br
.ti -1c
.RI "void \fBWithHeader_ShouldSupportChaining\fP ()"
.br
.ti -1c
.RI "void \fBWithQuery_ShouldAddQueryParameter\fP ()"
.br
.ti -1c
.RI "void \fBWithTimeout_ShouldSetTimeout\fP ()"
.br
.ti -1c
.RI "void \fBSetJsonContent_ShouldSetContent\fP ()"
.br
.ti -1c
.RI "void \fBSetStringContent_ShouldSetContent\fP ()"
.br
.ti -1c
.RI "void \fBSetFormContent_ShouldSetContent\fP ()"
.br
.ti -1c
.RI "void \fBSetBinaryContent_ShouldSetContent\fP ()"
.br
.ti -1c
.RI "void \fBBuildUrl_WithNoQueryParams_ShouldReturnUrl\fP ()"
.br
.ti -1c
.RI "void \fBBuildUrl_WithQueryParams_ShouldAppendQueryString\fP ()"
.br
.ti -1c
.RI "void \fBBuildUrl_WithExistingQueryString_ShouldAppendWithAmpersand\fP ()"
.br
.ti -1c
.RI "void \fBBuildUrl_ShouldEncodeSpecialCharacters\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUnit\fP tests for \fBApiRequest\fP and related classes\&. 
.PP
Definition at line \fB8\fP of file \fBApiRequestTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.BuildUrl_ShouldEncodeSpecialCharacters ()"

.PP
Definition at line \fB309\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.BuildUrl_WithExistingQueryString_ShouldAppendWithAmpersand ()"

.PP
Definition at line \fB294\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.BuildUrl_WithNoQueryParams_ShouldReturnUrl ()"

.PP
Definition at line \fB264\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.BuildUrl_WithQueryParams_ShouldAppendQueryString ()"

.PP
Definition at line \fB277\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Constructor_ShouldUppercaseMethod ()"

.PP
Definition at line \fB24\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Constructor_WithNullMethod_ShouldThrow ()"

.PP
Definition at line \fB34\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Constructor_WithNullUrl_ShouldThrow ()"

.PP
Definition at line \fB44\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Constructor_WithValidParameters_ShouldCreate ()"

.PP
Definition at line \fB13\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Delete_ShouldCreateDeleteRequest ()"

.PP
Definition at line \fB114\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Get_ShouldCreateGetRequest ()"

.PP
Definition at line \fB58\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Head_ShouldCreateHeadRequest ()"

.PP
Definition at line \fB124\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Options_ShouldCreateOptionsRequest ()"

.PP
Definition at line \fB134\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Patch_ShouldCreatePatchRequest ()"

.PP
Definition at line \fB104\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Post_ShouldCreatePostRequest ()"

.PP
Definition at line \fB69\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Post_WithBody_ShouldSetJsonContent ()"

.PP
Definition at line \fB80\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.Put_ShouldCreatePutRequest ()"

.PP
Definition at line \fB94\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.SetBinaryContent_ShouldSetContent ()"

.PP
Definition at line \fB246\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.SetFormContent_ShouldSetContent ()"

.PP
Definition at line \fB228\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.SetJsonContent_ShouldSetContent ()"

.PP
Definition at line \fB201\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.SetStringContent_ShouldSetContent ()"

.PP
Definition at line \fB215\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.WithHeader_ShouldAddHeader ()"

.PP
Definition at line \fB148\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.WithHeader_ShouldSupportChaining ()"

.PP
Definition at line \fB162\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.WithQuery_ShouldAddQueryParameter ()"

.PP
Definition at line \fB174\fP of file \fBApiRequestTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.ApiRequestTests\&.WithTimeout_ShouldSetTimeout ()"

.PP
Definition at line \fB188\fP of file \fBApiRequestTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
