.TH "Toolbox.Tests.Unit.Services.FileTransfer" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.Services.FileTransfer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFtpFileTransferServiceTests\fP"
.br
.RI "\fBUnit\fP tests for \fBFtpFileTransferService\fP\&. "
.ti -1c
.RI "class \fBSftpFileTransferServiceTests\fP"
.br
.RI "\fBUnit\fP tests for \fBSftpFileTransferService\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
