.TH "Toolbox.Core.Services.Cryptography" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Services.Cryptography
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAesCryptographyService\fP"
.br
.RI "\fBCryptography\fP service implementation using AES symmetric encryption\&. "
.ti -1c
.RI "class \fBBase64CryptographyService\fP"
.br
.RI "\fBCryptography\fP service implementation using Base64 encoding\&. "
.ti -1c
.RI "class \fBRsaCryptographyService\fP"
.br
.RI "\fBCryptography\fP service implementation using RSA asymmetric encryption\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
