.TH "Toolbox.Tests.Unit.BaseAsyncDisposableServiceTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.BaseAsyncDisposableServiceTests \- \fBUnit\fP tests for \fBBaseAsyncDisposableService\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseAsyncDisposableServiceTests\fP ()"
.br
.ti -1c
.RI "async Task \fBDisposeAsync_ShouldSetIsDisposed\fP ()"
.br
.ti -1c
.RI "async Task \fBDisposeAsync_ShouldCallDisposeAsyncCore\fP ()"
.br
.ti -1c
.RI "async Task \fBDisposeAsync_ShouldBeIdempotent\fP ()"
.br
.ti -1c
.RI "async Task \fBDisposeAsync_WithCancellation_ShouldPassCancellationToken\fP ()"
.br
.ti -1c
.RI "async Task \fBDisposeAsync_WhenCancelled_ShouldThrowOperationCanceledException\fP ()"
.br
.ti -1c
.RI "void \fBDispose_ShouldCallDisposeAsyncCore\fP ()"
.br
.ti -1c
.RI "async Task \fBDisposeAsync_ShouldBeThreadSafe\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUnit\fP tests for \fBBaseAsyncDisposableService\fP\&. 
.PP
Definition at line \fB9\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.BaseAsyncDisposableServiceTests ()"

.PP
Definition at line \fB13\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.Dispose_ShouldCallDisposeAsyncCore ()"

.PP
Definition at line \fB92\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SS "async Task Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.DisposeAsync_ShouldBeIdempotent ()"

.PP
Definition at line \fB45\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SS "async Task Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.DisposeAsync_ShouldBeThreadSafe ()"

.PP
Definition at line \fB105\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SS "async Task Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.DisposeAsync_ShouldCallDisposeAsyncCore ()"

.PP
Definition at line \fB32\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SS "async Task Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.DisposeAsync_ShouldSetIsDisposed ()"

.PP
Definition at line \fB19\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SS "async Task Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.DisposeAsync_WhenCancelled_ShouldThrowOperationCanceledException ()"

.PP
Definition at line \fB74\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.
.SS "async Task Toolbox\&.Tests\&.Unit\&.BaseAsyncDisposableServiceTests\&.DisposeAsync_WithCancellation_ShouldPassCancellationToken ()"

.PP
Definition at line \fB60\fP of file \fBBaseAsyncDisposableServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
