.TH "Toolbox.Tests.Unit.Extensions" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.Extensions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApiServiceCollectionExtensionsTests\fP"
.br
.RI "\fBUnit\fP tests for ApiServiceCollectionExtensions\&. "
.ti -1c
.RI "class \fBMailingServiceCollectionExtensionsTests\fP"
.br
.RI "\fBUnit\fP tests for MailingServiceCollectionExtensions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
