.TH "Toolbox.Tests.Regression" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Regression
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOptionsSchemaTests\fP"
.br
.RI "\fBRegression\fP tests for options classes to detect breaking changes in configuration schema\&. "
.ti -1c
.RI "class \fBTelemetryConstantsTests\fP"
.br
.RI "\fBRegression\fP tests for TelemetryConstants to detect breaking changes\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
