.TH "Toolbox.Tests.Unit.Extensions.ApiServiceCollectionExtensionsTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.Extensions.ApiServiceCollectionExtensionsTests \- \fBUnit\fP tests for ApiServiceCollectionExtensions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddHttpApi_WithConfigureAction_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApi_WithOptions_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApi_WithNullServices_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApi_WithNullConfigureAction_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiAnonymous_ShouldRegisterAnonymousService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithBearerToken_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithBearerToken_WithNullToken_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithBasicAuth_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithBasicAuth_WithNullUsername_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithApiKey_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithApiKey_WithQueryLocation_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithOAuth2_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApiWithOAuth2_WithNullClientId_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddHttpApi_MultipleCalls_ShouldNotDuplicate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUnit\fP tests for ApiServiceCollectionExtensions\&. 
.PP
Definition at line \fB12\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApi_MultipleCalls_ShouldNotDuplicate ()"

.PP
Definition at line \fB229\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApi_WithConfigureAction_ShouldRegisterService ()"

.PP
Definition at line \fB15\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApi_WithNullConfigureAction_ShouldThrow ()"

.PP
Definition at line \fB68\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApi_WithNullServices_ShouldThrow ()"

.PP
Definition at line \fB55\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApi_WithOptions_ShouldRegisterService ()"

.PP
Definition at line \fB35\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiAnonymous_ShouldRegisterAnonymousService ()"

.PP
Definition at line \fB81\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithApiKey_ShouldRegisterService ()"

.PP
Definition at line \fB155\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithApiKey_WithQueryLocation_ShouldRegisterService ()"

.PP
Definition at line \fB171\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithBasicAuth_ShouldRegisterService ()"

.PP
Definition at line \fB126\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithBasicAuth_WithNullUsername_ShouldThrow ()"

.PP
Definition at line \fB142\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithBearerToken_ShouldRegisterService ()"

.PP
Definition at line \fB97\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithBearerToken_WithNullToken_ShouldThrow ()"

.PP
Definition at line \fB113\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithOAuth2_ShouldRegisterService ()"

.PP
Definition at line \fB191\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.ApiServiceCollectionExtensionsTests\&.AddHttpApiWithOAuth2_WithNullClientId_ShouldThrow ()"

.PP
Definition at line \fB212\fP of file \fBApiServiceCollectionExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
