.TH "Toolbox.Core.Extensions" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Extensions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApiServiceCollectionExtensions\fP"
.br
.RI "Extension methods for registering API services with dependency injection\&. "
.ti -1c
.RI "class \fBCryptographyServiceCollectionExtensions\fP"
.br
.RI "Extension methods for IServiceCollection to configure cryptography services\&. "
.ti -1c
.RI "class \fBFileTransferServiceCollectionExtensions\fP"
.br
.RI "Extension methods for IServiceCollection to configure file transfer services\&. "
.ti -1c
.RI "class \fBMailingServiceCollectionExtensions\fP"
.br
.RI "Extension methods for registering mailing services with dependency injection\&. "
.ti -1c
.RI "class \fBOpenTelemetryExtensions\fP"
.br
.RI "Extension methods for configuring OpenTelemetry with \fBToolbox\fP instrumentation\&. "
.ti -1c
.RI "class \fBServiceCollectionExtensions\fP"
.br
.RI "Extension methods for IServiceCollection to configure \fBToolbox\fP services\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
