.TH "Toolbox.Core" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAbstractions\fP"
.br
.ti -1c
.RI "namespace \fBBase\fP"
.br
.ti -1c
.RI "namespace \fBExtensions\fP"
.br
.ti -1c
.RI "namespace \fBOptions\fP"
.br
.ti -1c
.RI "namespace \fBServices\fP"
.br
.ti -1c
.RI "namespace \fBTelemetry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
