.TH "Toolbox.Core.Base.BaseDisposableService" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Base.BaseDisposableService \- Abstract base class providing a thread-safe implementation of the dispose pattern with integrated telemetry support\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBToolbox\&.Core\&.Abstractions\&.IDisposableService\fP, and \fBToolbox\&.Core\&.Abstractions\&.IInstrumentedService\fP\&.
.PP
Inherited by \fBToolbox\&.Core\&.Base\&.BaseAsyncDisposableService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Releases all resources used by this service\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseDisposableService\fP (string serviceName, ILogger logger)"
.br
.RI "Initializes a new instance of the \fBBaseDisposableService\fP class\&. "
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.RI "Releases the unmanaged resources used by this service and optionally releases managed resources\&. "
.ti -1c
.RI "void \fBThrowIfDisposed\fP ()"
.br
.RI "Throws an ObjectDisposedException if this service has been disposed\&. "
.ti -1c
.RI "void \fBRecordOperation\fP (string operationName, double durationMs)"
.br
.RI "Records an operation metric with the specified name and duration\&. "
.ti -1c
.RI "Activity? \fBStartActivity\fP ([CallerMemberName] string operationName='')"
.br
.RI "Starts a new activity for the specified operation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBServiceName\fP\fR [get]\fP"
.br
.RI "Gets the unique name identifying this service instance\&.

.PP
A human-readable name for logging and diagnostics\&. "
.ti -1c
.RI "bool \fBIsDisposed\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether this service has been disposed\&.

.PP
\fRtrue\fP if the service has been disposed; otherwise, \fRfalse\fP\&. "
.ti -1c
.RI "ActivitySource \fBActivitySource\fP\fR [get]\fP"
.br
.RI "Gets the System\&.Diagnostics\&.ActivitySource for distributed tracing\&.

.PP
The activity source used to create spans for this service\&. "
.ti -1c
.RI "Meter \fBMeter\fP\fR [get]\fP"
.br
.RI "Gets the System\&.Diagnostics\&.Metrics\&.Meter for metrics collection\&.

.PP
The meter used to create instruments for this service\&. "
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class providing a thread-safe implementation of the dispose pattern with integrated telemetry support\&. 

This class implements \fBIDisposableService\fP and \fBIInstrumentedService\fP, providing a consistent foundation for building disposable services\&. 

.PP
Derived classes should override \fBDispose(bool)\fP to release their resources\&. The base implementation handles thread-safety and telemetry automatically\&. 

.PP
\fBSee also\fP
.RS 4
\fBIDisposableService\fP, \fBIInstrumentedService\fP

.PP
.RE
.PP

.PP
Definition at line \fB27\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Toolbox\&.Core\&.Base\&.BaseDisposableService\&.BaseDisposableService (string serviceName, ILogger logger)\fR [protected]\fP"

.PP
Initializes a new instance of the \fBBaseDisposableService\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIserviceName\fP The name identifying this service instance\&.
.br
\fIlogger\fP The logger for diagnostic output\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when \fIserviceName\fP  or \fIlogger\fP  is \fRnull\fP\&. 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Core\&.Base\&.BaseDisposableService\&.Dispose ()"

.PP
Releases all resources used by this service\&. This method is thread-safe and can be called multiple times\&. Only the first call will release resources\&. 
.PP
Definition at line \fB71\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "virtual void Toolbox\&.Core\&.Base\&.BaseDisposableService\&.Dispose (bool disposing)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Releases the unmanaged resources used by this service and optionally releases managed resources\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP \fRtrue\fP to release both managed and unmanaged resources; \fRfalse\fP to release only unmanaged resources\&. 
.RE
.PP

.PP
Override this method in derived classes to release resources\&. Always call the base implementation after releasing your resources\&. 

.PP
This method is thread-safe\&. The \fIdisposing\fP  parameter will only be \fRtrue\fP for the first caller when called concurrently\&. 
.PP
Reimplemented in \fBToolbox\&.Core\&.Base\&.BaseAsyncDisposableService\fP\&.
.PP
Definition at line \fB94\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "void Toolbox\&.Core\&.Base\&.BaseDisposableService\&.RecordOperation (string operationName, double durationMs)\fR [protected]\fP"

.PP
Records an operation metric with the specified name and duration\&. 
.PP
\fBParameters\fP
.RS 4
\fIoperationName\fP The name of the operation\&.
.br
\fIdurationMs\fP The duration in milliseconds\&.
.RE
.PP

.PP
Definition at line \fB130\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "Activity? Toolbox\&.Core\&.Base\&.BaseDisposableService\&.StartActivity ([CallerMemberName] string operationName = \fR''\fP)\fR [protected]\fP"

.PP
Starts a new activity for the specified operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIoperationName\fP The name of the operation\&. Defaults to the calling method name\&.
.RE
.PP
\fBReturns\fP
.RS 4
The started Activity if tracing is enabled; otherwise, \fRnull\fP\&. 
.RE
.PP

.PP
Definition at line \fB142\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "void Toolbox\&.Core\&.Base\&.BaseDisposableService\&.ThrowIfDisposed ()\fR [protected]\fP"

.PP
Throws an ObjectDisposedException if this service has been disposed\&. 
.PP
\fBExceptions\fP
.RS 4
\fIObjectDisposedException\fP Thrown when \fBIsDisposed\fP is \fRtrue\fP\&. 
.RE
.PP

.PP
Call this method at the beginning of public methods to ensure the service is still usable\&. 
.PP
Definition at line \fB120\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ActivitySource Toolbox\&.Core\&.Base\&.BaseDisposableService\&.ActivitySource\fR [get]\fP"

.PP
Gets the System\&.Diagnostics\&.ActivitySource for distributed tracing\&.

.PP
The activity source used to create spans for this service\&. 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.IInstrumentedService\fP\&.
.PP
Definition at line \fB59\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "bool Toolbox\&.Core\&.Base\&.BaseDisposableService\&.IsDisposed\fR [get]\fP"

.PP
Gets a value indicating whether this service has been disposed\&.

.PP
\fRtrue\fP if the service has been disposed; otherwise, \fRfalse\fP\&. 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.IDisposableService\fP\&.
.PP
Definition at line \fB56\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "Meter Toolbox\&.Core\&.Base\&.BaseDisposableService\&.Meter\fR [get]\fP"

.PP
Gets the System\&.Diagnostics\&.Metrics\&.Meter for metrics collection\&.

.PP
The meter used to create instruments for this service\&. 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.IInstrumentedService\fP\&.
.PP
Definition at line \fB62\fP of file \fBBaseDisposableService\&.cs\fP\&.
.SS "string Toolbox\&.Core\&.Base\&.BaseDisposableService\&.ServiceName\fR [get]\fP"

.PP
Gets the unique name identifying this service instance\&.

.PP
A human-readable name for logging and diagnostics\&. 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.IDisposableService\fP\&.
.PP
Definition at line \fB53\fP of file \fBBaseDisposableService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
