.TH "Toolbox.Tests.Integration.OpenTelemetryExtensionsTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Integration.OpenTelemetryExtensionsTests \- \fBIntegration\fP tests for OpenTelemetryExtensions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddToolboxInstrumentation_Tracing_ShouldAddActivitySource\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxInstrumentation_Metrics_ShouldAddMeter\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxOpenTelemetry_ShouldRegisterTelemetryOptions\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxOpenTelemetry_WithCustomOptions_ShouldApplyConfiguration\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxInstrumentation_WithNullBuilder_ShouldThrowArgumentNullException\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxOpenTelemetry_WithNullServices_ShouldThrowArgumentNullException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBIntegration\fP tests for OpenTelemetryExtensions\&. 
.PP
Definition at line \fB14\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Integration\&.OpenTelemetryExtensionsTests\&.AddToolboxInstrumentation_Metrics_ShouldAddMeter ()"

.PP
Definition at line \fB33\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.OpenTelemetryExtensionsTests\&.AddToolboxInstrumentation_Tracing_ShouldAddActivitySource ()"

.PP
Definition at line \fB17\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.OpenTelemetryExtensionsTests\&.AddToolboxInstrumentation_WithNullBuilder_ShouldThrowArgumentNullException ()"

.PP
Definition at line \fB86\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.OpenTelemetryExtensionsTests\&.AddToolboxOpenTelemetry_ShouldRegisterTelemetryOptions ()"

.PP
Definition at line \fB49\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.OpenTelemetryExtensionsTests\&.AddToolboxOpenTelemetry_WithCustomOptions_ShouldApplyConfiguration ()"

.PP
Definition at line \fB64\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.OpenTelemetryExtensionsTests\&.AddToolboxOpenTelemetry_WithNullServices_ShouldThrowArgumentNullException ()"

.PP
Definition at line \fB99\fP of file \fBOpenTelemetryExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
