.TH "Toolbox.Core.Abstractions" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Abstractions
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBServices\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIAsyncDisposableService\fP"
.br
.RI "Interface for services requiring asynchronous disposal with cancellation support\&. "
.ti -1c
.RI "interface \fBIDisposableService\fP"
.br
.RI "\fBBase\fP interface for disposable services providing lifecycle management\&. "
.ti -1c
.RI "interface \fBIInstrumentedService\fP"
.br
.RI "Interface for services that expose OpenTelemetry instrumentation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
