.TH "Toolbox.Tests.Regression.OptionsSchemaTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Regression.OptionsSchemaTests \- \fBRegression\fP tests for options classes to detect breaking changes in configuration schema\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBToolboxOptions_SectionName_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBToolboxOptions_DefaultValues_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBToolboxTelemetryOptions_SectionName_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBToolboxTelemetryOptions_DefaultValues_ShouldNotChange\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRegression\fP tests for options classes to detect breaking changes in configuration schema\&. 
.PP
Definition at line \fB8\fP of file \fBOptionsSchemaTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Regression\&.OptionsSchemaTests\&.ToolboxOptions_DefaultValues_ShouldNotChange ()"

.PP
Definition at line \fB17\fP of file \fBOptionsSchemaTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.OptionsSchemaTests\&.ToolboxOptions_SectionName_ShouldNotChange ()"

.PP
Definition at line \fB11\fP of file \fBOptionsSchemaTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.OptionsSchemaTests\&.ToolboxTelemetryOptions_DefaultValues_ShouldNotChange ()"

.PP
Definition at line \fB33\fP of file \fBOptionsSchemaTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.OptionsSchemaTests\&.ToolboxTelemetryOptions_SectionName_ShouldNotChange ()"

.PP
Definition at line \fB27\fP of file \fBOptionsSchemaTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
