.TH "C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/obj/Release/net10.0/Toolbox.Core.GlobalUsings.g.cs" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/micde/RiderProjects/Toolbox/src/Toolbox.Core/obj/Release/net10.0/Toolbox.Core.GlobalUsings.g.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
