.TH "Toolbox.Tests.Unit.Options.FileTransferOptionsTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.Options.FileTransferOptionsTests \- \fBUnit\fP tests for \fBFileTransferOptions\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetDefaultPort_ForFtp_ShouldReturn21\fP ()"
.br
.ti -1c
.RI "void \fBGetDefaultPort_ForFtps_ShouldReturn990\fP ()"
.br
.ti -1c
.RI "void \fBGetDefaultPort_ForSftp_ShouldReturn22\fP ()"
.br
.ti -1c
.RI "void \fBGetEffectivePort_WhenPortIsSet_ShouldReturnSetPort\fP ()"
.br
.ti -1c
.RI "void \fBGetEffectivePort_WhenPortIsNotSet_ShouldReturnDefaultPort\fP ()"
.br
.ti -1c
.RI "void \fBDefaultValues_ShouldBeCorrect\fP ()"
.br
.ti -1c
.RI "void \fBSectionName_ShouldBeCorrect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUnit\fP tests for \fBFileTransferOptions\fP\&. 
.PP
Definition at line \fB8\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.DefaultValues_ShouldBeCorrect ()"

.PP
Definition at line \fB84\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.GetDefaultPort_ForFtp_ShouldReturn21 ()"

.PP
Definition at line \fB11\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.GetDefaultPort_ForFtps_ShouldReturn990 ()"

.PP
Definition at line \fB24\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.GetDefaultPort_ForSftp_ShouldReturn22 ()"

.PP
Definition at line \fB37\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.GetEffectivePort_WhenPortIsNotSet_ShouldReturnDefaultPort ()"

.PP
Definition at line \fB67\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.GetEffectivePort_WhenPortIsSet_ShouldReturnSetPort ()"

.PP
Definition at line \fB50\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Options\&.FileTransferOptionsTests\&.SectionName_ShouldBeCorrect ()"

.PP
Definition at line \fB104\fP of file \fBFileTransferOptionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
