.TH "Toolbox.Core.Services.FileTransfer" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Services.FileTransfer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFtpFileTransferService\fP"
.br
.RI "File transfer service implementation using FTP/FTPS protocols\&. "
.ti -1c
.RI "class \fBSftpFileTransferService\fP"
.br
.RI "File transfer service implementation using SFTP protocol\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
