.TH "Toolbox.Tests.Unit.Extensions.MailingServiceCollectionExtensionsTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit.Extensions.MailingServiceCollectionExtensionsTests \- \fBUnit\fP tests for MailingServiceCollectionExtensions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddSmtpMailing_WithConfigureAction_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddSmtpMailing_WithOptions_ShouldRegisterService\fP ()"
.br
.ti -1c
.RI "void \fBAddSmtpMailing_WithNullServices_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddSmtpMailing_WithNullConfigureAction_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddSmtpMailing_WithNullOptions_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddGmailMailing_ShouldConfigureCorrectly\fP ()"
.br
.ti -1c
.RI "void \fBAddGmailMailing_WithNullEmail_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddGmailMailing_WithNullPassword_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddOutlookMailing_ShouldConfigureCorrectly\fP ()"
.br
.ti -1c
.RI "void \fBAddOutlookMailing_WithNullEmail_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddOutlookMailing_WithNullPassword_ShouldThrow\fP ()"
.br
.ti -1c
.RI "void \fBAddSmtpMailing_MultipleCalls_ShouldNotDuplicate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUnit\fP tests for MailingServiceCollectionExtensions\&. 
.PP
Definition at line \fB12\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddGmailMailing_ShouldConfigureCorrectly ()"

.PP
Definition at line \fB96\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddGmailMailing_WithNullEmail_ShouldThrow ()"

.PP
Definition at line \fB112\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddGmailMailing_WithNullPassword_ShouldThrow ()"

.PP
Definition at line \fB125\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddOutlookMailing_ShouldConfigureCorrectly ()"

.PP
Definition at line \fB138\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddOutlookMailing_WithNullEmail_ShouldThrow ()"

.PP
Definition at line \fB154\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddOutlookMailing_WithNullPassword_ShouldThrow ()"

.PP
Definition at line \fB167\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddSmtpMailing_MultipleCalls_ShouldNotDuplicate ()"

.PP
Definition at line \fB180\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddSmtpMailing_WithConfigureAction_ShouldRegisterService ()"

.PP
Definition at line \fB15\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddSmtpMailing_WithNullConfigureAction_ShouldThrow ()"

.PP
Definition at line \fB70\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddSmtpMailing_WithNullOptions_ShouldThrow ()"

.PP
Definition at line \fB83\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddSmtpMailing_WithNullServices_ShouldThrow ()"

.PP
Definition at line \fB57\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Unit\&.Extensions\&.MailingServiceCollectionExtensionsTests\&.AddSmtpMailing_WithOptions_ShouldRegisterService ()"

.PP
Definition at line \fB36\fP of file \fBMailingServiceCollectionExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
