.TH "Toolbox.Tests.Unit" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Unit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBExtensions\fP"
.br
.ti -1c
.RI "namespace \fBOptions\fP"
.br
.ti -1c
.RI "namespace \fBServices\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseAsyncDisposableServiceTests\fP"
.br
.RI "\fBUnit\fP tests for \fBBaseAsyncDisposableService\fP\&. "
.ti -1c
.RI "class \fBBaseDisposableServiceTests\fP"
.br
.RI "\fBUnit\fP tests for \fBBaseDisposableService\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
