.TH "Toolbox.Core.Abstractions.Services" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Abstractions.Services
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIApiService\fP"
.br
.RI "Defines the contract for HTTP API services\&. "
.ti -1c
.RI "interface \fBICryptographyService\fP"
.br
.RI "Interface for cryptography services providing text encryption and decryption\&. "
.ti -1c
.RI "interface \fBIFileTransferService\fP"
.br
.RI "Defines the contract for file transfer services supporting FTP and SFTP protocols\&. "
.ti -1c
.RI "interface \fBIMailingService\fP"
.br
.RI "Defines the contract for email sending services\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
