.TH "Toolbox.Tests.Regression.TelemetryConstantsTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Regression.TelemetryConstantsTests \- \fBRegression\fP tests for TelemetryConstants to detect breaking changes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBActivitySourceName_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBMeterName_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBVersion_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBAttributeNames_ShouldNotChange\fP ()"
.br
.ti -1c
.RI "void \fBMetricNames_ShouldNotChange\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRegression\fP tests for TelemetryConstants to detect breaking changes\&. 
.PP
Definition at line \fB8\fP of file \fBTelemetryConstantsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Regression\&.TelemetryConstantsTests\&.ActivitySourceName_ShouldNotChange ()"

.PP
Definition at line \fB11\fP of file \fBTelemetryConstantsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.TelemetryConstantsTests\&.AttributeNames_ShouldNotChange ()"

.PP
Definition at line \fB29\fP of file \fBTelemetryConstantsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.TelemetryConstantsTests\&.MeterName_ShouldNotChange ()"

.PP
Definition at line \fB17\fP of file \fBTelemetryConstantsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.TelemetryConstantsTests\&.MetricNames_ShouldNotChange ()"

.PP
Definition at line \fB38\fP of file \fBTelemetryConstantsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Regression\&.TelemetryConstantsTests\&.Version_ShouldNotChange ()"

.PP
Definition at line \fB23\fP of file \fBTelemetryConstantsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
