.TH "Toolbox.Core.Telemetry" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Telemetry
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTelemetryConstants\fP"
.br
.RI "Constants used for OpenTelemetry instrumentation across \fBToolbox\fP services\&. "
.ti -1c
.RI "class \fBToolboxActivitySource\fP"
.br
.RI "Provides a shared ActivitySource for distributed tracing across \fBToolbox\fP services\&. "
.ti -1c
.RI "class \fBToolboxMeter\fP"
.br
.RI "Provides a shared Meter and pre-defined instruments for metrics collection\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
