.TH "Toolbox.Tests.Integration.ServiceCollectionExtensionsTests" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Tests.Integration.ServiceCollectionExtensionsTests \- \fBIntegration\fP tests for ServiceCollectionExtensions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddToolboxCore_ShouldRegisterOptions\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxCore_WithConfiguration_ShouldApplyOptions\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxCore_FromConfiguration_ShouldBindOptions\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxCore_WithNullServices_ShouldThrowArgumentNullException\fP ()"
.br
.ti -1c
.RI "void \fBAddToolboxCore_WithNullConfigureAction_ShouldThrowArgumentNullException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBIntegration\fP tests for ServiceCollectionExtensions\&. 
.PP
Definition at line \fB12\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Toolbox\&.Tests\&.Integration\&.ServiceCollectionExtensionsTests\&.AddToolboxCore_FromConfiguration_ShouldBindOptions ()"

.PP
Definition at line \fB50\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.ServiceCollectionExtensionsTests\&.AddToolboxCore_ShouldRegisterOptions ()"

.PP
Definition at line \fB15\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.ServiceCollectionExtensionsTests\&.AddToolboxCore_WithConfiguration_ShouldApplyOptions ()"

.PP
Definition at line \fB30\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.ServiceCollectionExtensionsTests\&.AddToolboxCore_WithNullConfigureAction_ShouldThrowArgumentNullException ()"

.PP
Definition at line \fB86\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.
.SS "void Toolbox\&.Tests\&.Integration\&.ServiceCollectionExtensionsTests\&.AddToolboxCore_WithNullServices_ShouldThrowArgumentNullException ()"

.PP
Definition at line \fB73\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
