.TH "Toolbox.Core.Base" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Base
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseAsyncDisposableService\fP"
.br
.RI "Abstract base class providing asynchronous disposal with cancellation support and integrated telemetry\&. "
.ti -1c
.RI "class \fBBaseDisposableService\fP"
.br
.RI "Abstract base class providing a thread-safe implementation of the dispose pattern with integrated telemetry support\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
