.TH "Toolbox.Core.Services.FileTransfer.SftpFileTransferService" 3 "Version 1.0" "Toolbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toolbox.Core.Services.FileTransfer.SftpFileTransferService \- File transfer service implementation using SFTP protocol\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBToolbox\&.Core\&.Base\&.BaseAsyncDisposableService\fP, and \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSftpFileTransferService\fP (IOptions< \fBFileTransferOptions\fP > options, ILogger< SftpFileTransferService > logger)"
.br
.RI "Initializes a new instance of the \fBSftpFileTransferService\fP class\&. "
.ti -1c
.RI "\fBSftpFileTransferService\fP (\fBFileTransferOptions\fP options, ILogger< SftpFileTransferService > logger)"
.br
.RI "Initializes a new instance of the \fBSftpFileTransferService\fP class\&. "
.ti -1c
.RI "void \fBUploadOne\fP (string localPath, string remotePath, bool overwrite=true)"
.br
.RI "Uploads a single file to the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIlocalPath\fP The local file path to upload\&.
.br
\fIremotePath\fP The remote destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when local file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 "
.ti -1c
.RI "async Task \fBUploadOneAsync\fP (string localPath, string remotePath, bool overwrite=true, CancellationToken cancellationToken=default)"
.br
.RI "Uploads a single file to the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIlocalPath\fP The local file path to upload\&.
.br
\fIremotePath\fP The remote destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task representing the asynchronous operation\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when local file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 "
.ti -1c
.RI "int \fBUploadBatch\fP (IEnumerable<(string LocalPath, string RemotePath)> files, bool overwrite=true)"
.br
.RI "Uploads multiple files to the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (localPath, remotePath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.RE
.PP
\fBReturns\fP
.RS 4
The number of files successfully uploaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 "
.ti -1c
.RI "async Task< int > \fBUploadBatchAsync\fP (IEnumerable<(string LocalPath, string RemotePath)> files, bool overwrite=true, CancellationToken cancellationToken=default)"
.br
.RI "Uploads multiple files to the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (localPath, remotePath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task containing the number of files successfully uploaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 "
.ti -1c
.RI "void \fBDownloadOne\fP (string remotePath, string localPath, bool overwrite=true)"
.br
.RI "Downloads a single file from the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIremotePath\fP The remote file path to download\&.
.br
\fIlocalPath\fP The local destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when remote file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 "
.ti -1c
.RI "async Task \fBDownloadOneAsync\fP (string remotePath, string localPath, bool overwrite=true, CancellationToken cancellationToken=default)"
.br
.RI "Downloads a single file from the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIremotePath\fP The remote file path to download\&.
.br
\fIlocalPath\fP The local destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task representing the asynchronous operation\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when remote file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 "
.ti -1c
.RI "int \fBDownloadBatch\fP (IEnumerable<(string RemotePath, string LocalPath)> files, bool overwrite=true)"
.br
.RI "Downloads multiple files from the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (remotePath, localPath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.RE
.PP
\fBReturns\fP
.RS 4
The number of files successfully downloaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 "
.ti -1c
.RI "async Task< int > \fBDownloadBatchAsync\fP (IEnumerable<(string RemotePath, string LocalPath)> files, bool overwrite=true, CancellationToken cancellationToken=default)"
.br
.RI "Downloads multiple files from the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (remotePath, localPath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task containing the number of files successfully downloaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 "
.in -1c

Public Member Functions inherited from \fBToolbox\&.Core\&.Base\&.BaseAsyncDisposableService\fP
.in +1c
.ti -1c
.RI "ValueTask \fBDisposeAsync\fP ()"
.br
.ti -1c
.RI "async ValueTask \fBDisposeAsync\fP (CancellationToken cancellationToken)"
.br
.RI "Asynchronously releases resources with cancellation support\&.

.PP
\fBParameters\fP
.RS 4
\fIcancellationToken\fP A CancellationToken that can be used to cancel the disposal operation\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A ValueTask representing the asynchronous disposal operation\&.
.RE
.PP

.PP
This method allows for graceful shutdown with timeout support\&. If the cancellation token is triggered, the implementation should attempt to release critical resources immediately\&.  "
.in -1c

Public Member Functions inherited from \fBToolbox\&.Core\&.Base\&.BaseDisposableService\fP
.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Releases all resources used by this service\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async ValueTask \fBDisposeAsyncCore\fP (CancellationToken cancellationToken)"
.br
.RI "Performs application-defined async cleanup operations\&.

.PP
\fBParameters\fP
.RS 4
\fIcancellationToken\fP A CancellationToken that can be used to cancel the disposal operation\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A ValueTask representing the asynchronous operation\&.
.RE
.PP

.PP
Override this method to release async resources such as streams, database connections, or other async-disposable objects\&.  "
.in -1c

Protected Member Functions inherited from \fBToolbox\&.Core\&.Base\&.BaseAsyncDisposableService\fP
.in +1c
.ti -1c
.RI "\fBBaseAsyncDisposableService\fP (string serviceName, ILogger logger)"
.br
.RI "Initializes a new instance of the \fBBaseAsyncDisposableService\fP class\&. "
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.in -1c

Protected Member Functions inherited from \fBToolbox\&.Core\&.Base\&.BaseDisposableService\fP
.in +1c
.ti -1c
.RI "\fBBaseDisposableService\fP (string serviceName, ILogger logger)"
.br
.RI "Initializes a new instance of the \fBBaseDisposableService\fP class\&. "
.ti -1c
.RI "void \fBThrowIfDisposed\fP ()"
.br
.RI "Throws an ObjectDisposedException if this service has been disposed\&. "
.ti -1c
.RI "void \fBRecordOperation\fP (string operationName, double durationMs)"
.br
.RI "Records an operation metric with the specified name and duration\&. "
.ti -1c
.RI "Activity? \fBStartActivity\fP ([CallerMemberName] string operationName='')"
.br
.RI "Starts a new activity for the specified operation\&. "
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBToolbox\&.Core\&.Base\&.BaseDisposableService\fP
.in +1c
.ti -1c
.RI "string \fBServiceName\fP\fR [get]\fP"
.br
.RI "Gets the unique name identifying this service instance\&.

.PP
A human-readable name for logging and diagnostics\&. "
.ti -1c
.RI "bool \fBIsDisposed\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether this service has been disposed\&.

.PP
\fRtrue\fP if the service has been disposed; otherwise, \fRfalse\fP\&. "
.ti -1c
.RI "ActivitySource \fBActivitySource\fP\fR [get]\fP"
.br
.RI "Gets the System\&.Diagnostics\&.ActivitySource for distributed tracing\&.

.PP
The activity source used to create spans for this service\&. "
.ti -1c
.RI "Meter \fBMeter\fP\fR [get]\fP"
.br
.RI "Gets the System\&.Diagnostics\&.Metrics\&.Meter for metrics collection\&.

.PP
The meter used to create instruments for this service\&. "
.in -1c
.SH "Detailed Description"
.PP 
File transfer service implementation using SFTP protocol\&. 

This service provides secure file upload and download capabilities using the SFTP protocol\&. It supports both password and private key authentication\&. 

.PP
Uses SSH\&.NET library for SFTP operations\&. 

.PP
\fBSee also\fP
.RS 4
\fBIFileTransferService\fP

.PP
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.SftpFileTransferService (IOptions< \fBFileTransferOptions\fP > options, ILogger< SftpFileTransferService > logger)"

.PP
Initializes a new instance of the \fBSftpFileTransferService\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIoptions\fP The file transfer options\&.
.br
\fIlogger\fP The logger instance\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when options or logger is null\&.
.br
\fIArgumentException\fP Thrown when host or username is empty\&.
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.SftpFileTransferService (\fBFileTransferOptions\fP options, ILogger< SftpFileTransferService > logger)"

.PP
Initializes a new instance of the \fBSftpFileTransferService\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIoptions\fP The file transfer options\&.
.br
\fIlogger\fP The logger instance\&.
.RE
.PP

.PP
Definition at line \fB87\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override async ValueTask Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.DisposeAsyncCore (CancellationToken cancellationToken)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Performs application-defined async cleanup operations\&.

.PP
\fBParameters\fP
.RS 4
\fIcancellationToken\fP A CancellationToken that can be used to cancel the disposal operation\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A ValueTask representing the asynchronous operation\&.
.RE
.PP

.PP
Override this method to release async resources such as streams, database connections, or other async-disposable objects\&.  
.PP
Reimplemented from \fBToolbox\&.Core\&.Base\&.BaseAsyncDisposableService\fP\&.
.PP
Definition at line \fB512\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "int Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.DownloadBatch (IEnumerable<(string RemotePath, string LocalPath)> files, bool overwrite = \fRtrue\fP)"

.PP
Downloads multiple files from the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (remotePath, localPath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.RE
.PP
\fBReturns\fP
.RS 4
The number of files successfully downloaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB416\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "async Task< int > Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.DownloadBatchAsync (IEnumerable<(string RemotePath, string LocalPath)> files, bool overwrite = \fRtrue\fP, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Downloads multiple files from the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (remotePath, localPath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task containing the number of files successfully downloaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB463\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "void Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.DownloadOne (string remotePath, string localPath, bool overwrite = \fRtrue\fP)"

.PP
Downloads a single file from the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIremotePath\fP The remote file path to download\&.
.br
\fIlocalPath\fP The local destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when remote file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB307\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "async Task Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.DownloadOneAsync (string remotePath, string localPath, bool overwrite = \fRtrue\fP, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Downloads a single file from the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIremotePath\fP The remote file path to download\&.
.br
\fIlocalPath\fP The local destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing local files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task representing the asynchronous operation\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when remote file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB360\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "int Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.UploadBatch (IEnumerable<(string LocalPath, string RemotePath)> files, bool overwrite = \fRtrue\fP)"

.PP
Uploads multiple files to the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (localPath, remotePath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.RE
.PP
\fBReturns\fP
.RS 4
The number of files successfully uploaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB211\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "async Task< int > Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.UploadBatchAsync (IEnumerable<(string LocalPath, string RemotePath)> files, bool overwrite = \fRtrue\fP, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Uploads multiple files to the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Collection of tuples containing (localPath, remotePath) pairs\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task containing the number of files successfully uploaded\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when files collection is null\&.
.br
\fIAggregateException\fP Thrown when one or more transfers fail\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB258\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "void Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.UploadOne (string localPath, string remotePath, bool overwrite = \fRtrue\fP)"

.PP
Uploads a single file to the remote server\&.

.PP
\fBParameters\fP
.RS 4
\fIlocalPath\fP The local file path to upload\&.
.br
\fIremotePath\fP The remote destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when local file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB95\fP of file \fBSftpFileTransferService\&.cs\fP\&.
.SS "async Task Toolbox\&.Core\&.Services\&.FileTransfer\&.SftpFileTransferService\&.UploadOneAsync (string localPath, string remotePath, bool overwrite = \fRtrue\fP, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Uploads a single file to the remote server asynchronously\&.

.PP
\fBParameters\fP
.RS 4
\fIlocalPath\fP The local file path to upload\&.
.br
\fIremotePath\fP The remote destination path\&.
.br
\fIoverwrite\fP Whether to overwrite existing files\&.
.br
\fIcancellationToken\fP Cancellation token\&.
.RE
.PP
\fBReturns\fP
.RS 4
A task representing the asynchronous operation\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentNullException\fP Thrown when paths are null\&.
.br
\fIFileNotFoundException\fP Thrown when local file doesn't exist\&.
.br
\fIIOException\fP Thrown when transfer fails\&.
.RE
.PP
 
.PP
Implements \fBToolbox\&.Core\&.Abstractions\&.Services\&.IFileTransferService\fP\&.
.PP
Definition at line \fB152\fP of file \fBSftpFileTransferService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Toolbox from the source code\&.
